blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/bscholer/media-ingest-pi/blob/main/README.md
    about: Check the documentation for setup and usage instructions
  - name: Discussions
    url: https://github.com/bscholer/media-ingest-pi/discussions
    about: Ask questions and discuss ideas with the community

